[TAAS-21] Add support for global_clusters
UN-OCHA/taas pull request #15
Opened 2017-03-24 03:43 UTC by pjf

This adds support for global clusters, which are blessedly simple. The sheet they load from is [here](https://docs.google.com/spreadsheets/d/1SxSircxhXMZCe0PWafCht-whjBdI9UqoeFeSUbiLGc4/edit#gid=0).

Sample output:

```
{
    "acryonym": "SHL", 
    "group": "Global Cluster", 
    "homepage": "https://www.sheltercluster.org/", 
    "id": "4", 
    "label": "Emergency Shelter and NFI"
}
```

Things to note:

- We have no global clusters API endpoint at the moment. The closest is `bundles`, but it serves a very different and more complex set of data.
- The `group` is always "Global Cluster" or "Area of Responsibility". These feel like they should be machine-friendly terms. Should they have links to anywhere?
- I'm not exporting "date created" or similar columns, since they're just asking to be incorrectly updated.
- We're using the HRinfo ID for now, but we may wish to create our own ID column and use that.

2017-03-30 13:27 UTC, pjf commented
This has feedback [in JIRA](https://humanitarian.atlassian.net/browse/TAAS-21) that I need to review before it can be merged.

2017-03-31 13:30 UTC, andrejverity commented
Comment and attempt at moving the decision forward left in the JIRA ticket

2017-04-02 11:52 UTC, pjf commented
@andrejverity : You are *wonderful*!

Updated based upon JIRA discussion, was really just changing `group` to `group_type` in the output, so we now have:

```
  {
        "acryonym": "SHL", 
        "group_type": "Cluster", 
        "homepage": "https://www.sheltercluster.org/", 
        "id": "4", 
        "label": "Emergency Shelter and NFI"
    }
```

If you think this looks good, then I entreat you to press the "merge pull request" button (using all the defaults it gives you will be fine). :)

2017-04-03 07:55 UTC, emmajane requested changes

2017-04-03 07:55 UTC, emmajane commented on taas/config.yml
> +                acryonym: ACRONYM
Typo: `acryonym` needs to be updated to `acronym`

2017-04-04 04:07 UTC, pjf commented on taas/config.yml
> +                acryonym: ACRONYM
This is why code review is so fabulous. :)

♥

2017-04-04 04:09 UTC, pjf commented on taas/config.yml
> +                acryonym: ACRONYM
Fixed in ef7599a. :)

2017-04-04 05:54 UTC, merged